### ISSUE TITLE
Adding Korean translation

### ISSUE THREAD

**Issue by halcyonera** [geometer/FBReaderJ#317]
I finished translating _fbreader-en.xml_ and _zlibrary-en.xml_ but I don't know how to do with it. Should I send this to someone? I didn't translate _intro.html_ on purpose because some CJK document files won't be displayed properly with default encoding setting.

**Comment by geometer** [comment]
Hi,

Thank you! I received your message with Korean resources but looks like there is some problem because you inserted translated text directly into the message body. My mail program does not process it correctly. Could you please send it again as attachment to geometer@fbreader.org? 

Alternatively you can create pull request here on github. If you are not familiar with github just send me the files via email, this is absolutely ok.

As for intro.html, if you prepare some text I can generate ePub that would be used by FBReader and send it back to you for verification.

Regards,

-- Nikola

**Comment by geometer** [comment]
It was added several versions ago, thank you!
