### ISSUE TITLE
empty-line tag is not displayed properly

### ISSUE THREAD

**Issue by link2xt** [geometer/FBReaderJ#465]
```
<?xml version="1.0" encoding="UTF-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
<body>
    <title><p>title</p></title>
    <section><p>abc<empty-line />def</p></section>
</body>
</FictionBook>
```

FBReader on Android displays "abc" only, Linux version does not display anything but title. Cool Reader displays document correctly.

**Comment by geometer** [comment]
Good point, thanks. The parser did not expect empty-line tag inside a paragraph. Fixed in FBReader for Android 2.8.5/for iOS 1.0.2. Sorry, it is not open-source at the moment.

**Comment by yuriifabirovskyi** [comment]
Why it is not open source?

**Comment by geometer** [comment]
Unfair use of GPL code became common practice last years.

**Comment by dbdean** [comment]
This is unfortunate, but good to see it has been acknowledged by the author. I started using fbreader over moon+reader *because* it was open source.

It looks like someone is maintaining a recent fork at https://github.com/benetech/FBReaderJ as GoRead: http://goread.org/, and CoolReader might also be an alternative for people who want an open-source ereader: https://sourceforge.net/projects/crengine/, https://play.google.com/store/apps/details?id=org.coolreader&hl=en.

**Comment by yuriifabirovskyi** [comment]
@dbdean Thanks. I will try Go Read.:)
